name: nuget

on:
  push:
    tags:
      - 'v*'  # ä½¿ç”¨ v å¼€å¤´çš„ tag

jobs:
  nuget:
    name: nuget
    runs-on: windows-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      # ========== ğŸ”§ å®‰è£… .NET 6/8/9 SDK ==========
      - name: Setup .NET SDKs (6.0, 8.0, 9.0, 10.0)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            8.0.x
            9.0.x
            10.0.x

      # ========== ğŸ“¦ è¿˜åŸä¾èµ– ==========
      - name: Restore
        run: dotnet restore MapLib/MapLib.csproj

      # ========== ğŸ”§ æ„å»º ==========
      - name: Build
        run: |
          dotnet build MapLib/MapLib.csproj --configuration Release --no-restore /p:Pack=true

      # ========== ğŸ“¦ æ‰“åŒ… NuGet ==========
      - name: Pack
        run: |
          dotnet pack MapLib/MapLib.csproj --configuration Release --no-restore --no-build /p:Pack=true --output \tom

      # ========== ğŸš€ å‘å¸ƒåˆ° NuGet ==========
      - name: Push
        run: |
          dotnet nuget push \tom\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate